blank_issues_enabled: false
contact_links:
  - name: ❓ Questions / Feedback
    url: https://github.com/ngocthanhdev81/ViKey-Telex/discussions/new/choose
    about: Post your questions or feedback in the discussions panel
